-- Sales & Revenue Analysis
-- Calculate the total revenue generated by each store.

with cte as (select c.store_id, s.address_id, p.amount, a.address
from payment as p,
     customer as c,
     store as s,
     address as a
where p.customer_id = c.customer_id and c.store_id = s.store_id and a.address_id = s.address_id)

select address, sum(amount) as total from cte group by address order by total desc;